### ISSUE TITLE
Help for ros2 ci on mac platform

### ISSUE THREAD

**Issue by minggangw** [ros2/ci#104]
Hi all,

Now, we are developing a Node.js client named [rclnodejs](https://github.com/RobotWebTools/rclnodejs) of ros2.0, and we want it can support Linux, MacOS and Windows platforms. But we encounter a problem that we can't find a suitable ci service on mac, actually we have tried travic-ci (it has a maximum 50min build limitation) and circleci (doesn't have a free plan on mac).

I am wondering if we can leverage the ci of http://ci.ros2.org/, or do you have some better suggestions? Your help is appreciated!

Minggang

**Comment by dirk-thomas** [comment]
We use Jenkins with our own nodes for each targeted platform. The current CI farm is http://ci.ros2.org/ Atm we are not able to provide access to the machines but if you would like us to run some jobs on your public repositories we are happy to do so.

In the future we will likely provide repository specific CI jobs for every registered ROS package (http://build.ros2.org/). For now that instance only runs the jobs for creating Debian packages.

**Comment by minggangw** [comment]
Hi @dirk-thomas thanks for your quick response, that's helpful and we will approach you if we have some tasks to be run.

**Comment by dirk-thomas** [comment]
I will close this ticket for now since there is nothing to be done atm. Please feel free to comment on it afterwards.
