### ISSUE TITLE
OpenSplice not being found on Dosa.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ci#113]
I've pulled https://github.com/ADLINK-IST/opensplice/releases/download/OSPL_V6_7_171127OSS_RELEASE/PXXX-VortexOpenSplice-6.7.171127OSS-HDE-x86_64.darwin10_clang-release-installer.tar.gz onto to Dosa and exported `OSPL_HOME` to in the .bashrc.

This is sufficient for builds in a local ROS2 workspace to pick up and successfully build rmw_opensplice_cpp but when trying to run CI with opensplice I get the following failure http://ci.ros2.org/job/test_ci_osx/31/

It could be that CI either doesn't pick up variables set in .bash_profile/.bashrc or that its filtering them out.

There are local test failures when using this latest opensplice version so I don't think sorting this out is a priority for the current release window.

**Comment by mikaelarguedas** [comment]
Can you post the list of test failures somewhere?

Is it possible that Jenkins runs job with another user so the bash profile used is different?

**Comment by nuclearsandwich** [comment]
> Is it possible that Jenkins runs job with another user so the bash profile used is different?

No, both my local workspace and the Jenkins process run as the `osrf` user.

**Comment by nuclearsandwich** [comment]
Re-running tests into a log file now.

**Comment by mikaelarguedas** [comment]
@nuclearsandwich should this be closed now that https://github.com/ros2/ci/pull/116 has merged?
