### ISSUE TITLE
7zip unpack fails

### ISSUE THREAD

**Issue by jeising** [ros2/ci#126]
Under windows while unpacking the binary package with 7zip a strange behaviour appears. Windows is not able to read certain files properly any more. More details are described in this issue:

https://github.com/ros2/rviz/issues/208

There is also a suggestion mentioned what causes this issue and could fix it.

> @greimela-si:
> 
> The real cause seems to be the X file attribute.
>
> Reading the file fails if the X attribute is set and the A attribute is not set.
> This is why I originally thought that the A attribute might be responsible.

**Comment by nuclearsandwich** [comment]
Linked below, as far as I can tell, is how we currently build our Windows archives. Pull requests or suggestions are welcome.

https://github.com/ros2/ci/blob/master/ros2_batch_job/packaging.py#L167-L184

**Comment by mikaelarguedas** [comment]
As a workaround: Instructions have been updated to advise users to use the Windows explorer for extraction

**Comment by wjwwood** [comment]
Thanks @mikaelarguedas!

**Comment by clalancette** [comment]
Given the age of this issue, I'm going to close this out.  If you are still having a problem, please feel free to open a new issue.
