### ISSUE TITLE
Archives referencing skipped packages' local_setup.bat

### ISSUE THREAD

**Issue by dhood** [ros2/ci#156]
Some packages included in `ros2.repos` are not built for windows, but they still seem to end up in the `prefix.bat` included in the fat archive. This causes the following output for users which it would be better to avoid if possible.

```
C:\Users\osrf\Downloads\ros2_package_ospl_home3\ros2-windows>call prefix.bat
not found: "C:\Users\osrf\Downloads\ros2_package_ospl_home3\ros2-windows\share/rttest/local_setup.bat"
not found: "C:\Users\osrf\Downloads\ros2_package_ospl_home3\ros2-windows\share/tlsf/local_setup.bat"
not found: "C:\Users\osrf\Downloads\ros2_package_ospl_home3\ros2-windows\share/tlsf_cpp/local_setup.bat"
not found: "C:\Users\osrf\Downloads\ros2_package_ospl_home3\ros2-windows\share/pendulum_control/local_setup.bat"
```

**Comment by dirk-thomas** [comment]
The requested change colcon/colcon-core#13 made this visible. I think letting the user know about it makes sense. Maybe we should ignore those packages on Windows (e.g. by placing an `IGNORE` marker file in their directories)?

**Comment by dhood** [comment]
Yeah I agree that for source builds this visibility makes sense, it's just misleading in the specific case of the packaging job.

The packaging job never used to install anything in the `share` directory for packages that got skipped by CMake.

e.g.:
```
$ cd ~/Downloads/ros2-osx-beta1
$ ls share | grep pendulum
pendulum_msgs

$ cd ~/Downloads/ros2-osx-colcon-bash-fix/
$ ls share | grep pendulum
pendulum_control
pendulum_msgs
```

Do you think it is possible to restore that behaviour (technically)? If so I think that would be preferred over adding ignore markers (the skip in cmake is nicely self-contained and self-describing and so should be sufficient)

**Comment by dirk-thomas** [comment]
> Do you think it is possible to restore that behaviour (technically)?

What exact behavior do you want to "restore" / are you looking for? Revert the referenced patch and don't output a message (until `COLCON_TRACE` is set)?

**Comment by dirk-thomas** [comment]
So when a package specific setup file doesn't exist you want the prefix script to not complain about it. For this case that makes sense. But that will also apply to other cases: e.g. you build and install a package B but not its dependency A. Then the resulting prefix script should not print a message that A isn't present.

We can certainly change it that way - we just have to be certain that this is the way we want it to be in *all* the cases which have the same "state".

**Comment by dirk-thomas** [comment]
Currently the build tool also checks that these files actually exist (https://github.com/colcon/colcon-core/blob/f093f0bcffe2f0d1ea66d434e40fcad95638cee0/colcon_core/shell/sh.py#L84-L96) before generating the prefix script. So I am not yet sure how this gets into the state and how we could distinguish the case described.
