### ISSUE TITLE
Stop building the tests in packaging jobs?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ci#163]
We build the tests of all packages in the packaging jobs but we don't test them.
Is there a drawback if we stop building the tests? (we would keep building the bridge and test it)

**Comment by dhood** [comment]
not that I can see, unless we particularly value building tests in RelWithDebInfo. Just a copy-paste accident in https://github.com/ros2/ci/commit/72fdf479bf80f37fbe0e43da616e0fe59d09b845#diff-ff5a69e3fa8788343837457e9dd458f8L45 I imagine, unless it was intentional @dirk-thomas ?
