### ISSUE TITLE
turtlebot jobs should run tests only on the packages from the turtlebot repos file

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ci#173]
The turtlebot jobs, (nightly and CI) run tests for all packages in ros2.repos.

We could reduce the job times significantly if we were only running the tests of the packages on the turtlebot repos file.
This could also allow us to exercise the overlay logic if we were to split the logic into:
- build a workspace with the ros2.repos file
- build an overlay workspace with the turtlebot2.repos file
- run tests on the overlay workspace
(this proposal assumes that we still build everything from source)

**Comment by clalancette** [comment]
The turtlebot jobs are now gone, so closing this out.
