### ISSUE TITLE
Build C++ application failed with last successful package on Linux

### ISSUE THREAD

**Issue by minggangw** [ros2/ci#187]
Hi there,

Recently I noticed that there was a persistent link error when compiling a simple example written in C++.

- ROS 2 Package: [Last Successful Artifacts](https://ci.ros2.org/view/packaging/job/packaging_linux/lastSuccessfulBuild/artifact/ws/ros2-package-linux-x86_64.tar.bz2)
- Platform: Ubuntu 16.04
- Project: https://github.com/RobotWebTools/rclnodejs/tree/develop/test/cpp OR https://github.com/ros2/examples
- Error:
``` bash
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /home/minggang/Downloads/ros2-linux/lib/libfastrtps.so.1.5.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtinyxml2.so.6, needed by /home/minggang/Downloads/ros2-linux/lib/libfastrtps.so.1.5.0, not found (try using -rpath or -rpath-link)
/home/minggang/Downloads/ros2-linux/lib/libfastrtps.so.1.5.0: undefined reference to `BUF_MEM_free@OPENSSL_1_1_0'
/home/minggang/Downloads/ros2-linux/lib/libfastrtps.so.1.5.0: undefined reference to `tinyxml2::XMLNode::Value() const'
/home/minggang/Downloads/ros2-linux/lib/libfastrtps.so.1.5.0: undefined reference to `EVP_PKEY_new@OPENSSL_1_1_0'
/home/minggang/Downloads/ros2-linux/lib/libfastrtps.so.1.5.0: undefined reference to `X509_STORE_CTX_free@OPENSSL_1_1_0'
```
Detailed log see [here](https://travis-ci.org/RobotWebTools/rclnodejs/builds/390638890?utm_source=github_status&utm_medium=notification)

More information:

```bash
$ldd libfastrtps.so.1.5.0 
./libfastrtps.so.1.5.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./libfastrtps.so.1.5.0)
	linux-vdso.so.1 =>  (0x00007ffce69ba000)
	libfastcdr.so.1 => /home/minggang/Downloads/ros2-linux/lib/libfastcdr.so.1 (0x00007f9326b83000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9326966000)
	libcrypto.so.1.1 => not found
	libtinyxml2.so.6 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f93265e4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f93263ce000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9326004000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9327222000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9325cfb000)
```

This problem can not be reproduced on macOS and Windows, is there any dependency change?

**Comment by mikaelarguedas** [comment]
@minggangw Is this something you faced for a while or did it appear in the last few days ?

Our CI shifted from Ubuntu Xenial to Ubuntu Bionic [on Friday](https://github.com/ros2/ci/pull/148) to prepare for the [upcoming Bouncy release](https://github.com/ros-infrastructure/rep/blob/master/rep-2000.rst#bouncy-bolson-june-2018---june-2019).

We have [some jobs still running xenial](https://ci.ros2.org/view/nightly/job/nightly_xenial_linux_release/), but they don't produce artifacts at the moment.

Sorry for the inconvenience, I likely should've announced it on discourse before deploying it.

**Comment by minggangw** [comment]
I checked the error on [travis-ci](https://travis-ci.org/RobotWebTools/rclnodejs/pull_requests), it appeared around last Friday(6/8). Will it support Xenial after the switch from Xenial to Bionic? Thanks!

**Comment by mikaelarguedas** [comment]
ROS Bouncy will provide debian packages only for Bionic.
We will keep building from source and testing the core on Xenial for Bouncy, but are not planning on producing binaries for it.

I opened https://github.com/ros2/ci/pull/188 to discuss the possibility of providing Bouncy tarballs for Xenial.

**Comment by minggangw** [comment]
Got it, thanks! I hope the ci farm can still have Bouncy tarball for Xenial as Bionic is quite new and it may take some time to migrate.

**Comment by mikaelarguedas** [comment]
@minggangw starting tomorrow, xenial archives will be generated nightly and available at https://ci.ros2.org/view/packaging/job/packaging_xenial_linux/lastSuccessfulBuild/artifact/
