### ISSUE TITLE
compile options for ros2 builds

### ISSUE THREAD

**Issue by dejanpan** [ros2/ci#190]
@nuclearsandwich @dirk-thomas 

I've noticed in one of your build job outputs for ros2: http://build.ros2.org/view/Abin_uX64/job/Abin_uX64__rclcpp__ubuntu_xenial_amd64__binary/11/consoleText that you use the following compile options:
`-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2  -Wall -Wextra -Wpedantic`.

We recently also came across this article: https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc/ and noticed in particular these flags:
1. -fstack-protector-strong
1. -Werror=format-security
1. -D_FORTIFY_SOURCE=2 

Q1: where do you set these above flags because I could not really spot them in any CMakeLists files in any of the major repos on https://github.com/ros2.

Q2: are you aware that any of above options introduces a significant runtime performance overhead?

**Comment by mikaelarguedas** [comment]
> Q1:

These set of flags can be split in 2 parts, the ones we set in CMake, and the ones set by the debian packaging tools (dpkg).

- `-Wall -Wextra -Wpedantic` is set by us: https://github.com/ros2/rclcpp/blob/1b87970d8e6370c46f033f04b538591f27a163b3/rclcpp/CMakeLists.txt#L27
- `-O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2` are the default flags added by the release tooling:
You can find the list of flags and their default state (added by default or not) at https://manpages.debian.org/testing/dpkg-dev/dpkg-buildflags.1.en.html#hardening

> Q2

I didn't research the actual performance hit introduced by the default debian flags so I don't have an answer ATM.

**Comment by dejanpan** [comment]
@mikaelarguedas thanks a lot. I am a bit surprised  because the flags set by dpkg do seem to be somewhat special (according to redhat post) and thus make quite a difference between code compilled from source and the generated debians.

It would be interesting to see if there is any perf hit. I will bookmark this and see if I can look it up in the next weeks.

**Comment by dejanpan** [comment]
@mikaelarguedas sorry one more Q - did you ever consider adding those same flags from dpkg to ros2 CmakeLists.txt? Because if they anyways end up in debians...

**Comment by mikaelarguedas** [comment]
> sorry one more Q - did you ever consider adding those same flags from dpkg to ros2 CmakeLists.txt? Because if they anyways end up in debians...

Not that I know of, some potential reasons (I'm guessing I don't remember discussing it):
- some of these flags are tied to the build type and we would need to duplicate the dpkg logic to set different flags for each build type
- some are also gcc specific so would need extra handling to pass their equivalent (if any) to the compiler used by the other platforms
- as this is very platform specific, letting the platform tools use what is the common default for their packaging process seems sensible. If the next version of gcc comes with new / better optimization or protection flags that are deemed valuable, we would need to monitor closely dpkg changes and touch all our CMakeLists to keep the flag duplication up-to-date

**Comment by dirk-thomas** [comment]
I assume the questions have been answered an will go ahead an close the ticket. Please feel free to comment. If there is any action item remaining this can be reopened.
