### ISSUE TITLE
Undefined name 'main' in ./ros2_batch_job/packaging.py

### ISSUE THREAD

**Issue by cclauss** [ros2/ci#205]
flake8 testing of https://github.com/ros2/ci on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ros2_batch_job/packaging.py:200:14: F821 undefined name 'main'
    sys.exit(main())
             ^
1     F821 undefined name 'main'
1
```

**Comment by dirk-thomas** [comment]
The `__main__` entry point doesn't seem to be usable for that Python module. Please provide a PR removing it which should resolve the `flake8` error.
