### ISSUE TITLE
Install pytest, setuptools from apt on Bionic

### ISSUE THREAD

**Issue by sloretz** [ros2/ci#230]
The [Linux Development Setup](https://index.ros.org/doc/ros2/Linux-Development-Setup/) instructions currently say to install pytest and setuptools from pip on xenial. It sounds like they could be installed via apt instead.

```
# [Ubuntu 16.04] install extra packages not available or recent enough on Xenial
python3 -m pip install -U \
  pytest \
  pytest-cov \
  pytest-runner \
  setuptools
```

However, CI currently installs all of these from pip. This issue is to change CI to install these from apt and see if it works.

See also ros2/ros2_documentation#67
If the dependencies from apt work then this PR will need to be undone: ros2/ros2_documentation#70

**Comment by clalancette** [comment]
This was done years ago, so closing this out.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/inconsistency-in-flake8-between-ros2-source-builds-ci-ros2-org-and-build-ros2-org-for-prs/11079/1
