### ISSUE TITLE
fix name of armhf archive

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ci#298]
The packaging job for `armhf` produces an archive named `aarch64`.

**Comment by nuclearsandwich** [comment]
I was looking at this, and it's not actually the name of the armhf jobs. It's actually building 64-bit arm executables.

**Comment by nuclearsandwich** [comment]
Also for the record this is where the name is set. https://github.com/ros2/ci/blob/fc97f6c3416d997866bbcf9b58fb34efd96066d9/ros2_batch_job/packaging.py#L169

It may be that fixing the container architecture will also fix the name.

**Comment by dirk-thomas** [comment]
> It's actually building 64-bit arm executables.

We should probably pull the archive from the release then?

**Comment by clalancette** [comment]
This was fixed a while ago with all of the changes for armhf, so I'll close this out.
