### ISSUE TITLE
Missing ros-dashing-ros2action in ros-dashing-desktop deb package

### ISSUE THREAD

**Issue by slessans** [ros2/ci#300]
Not sure if this is the correct repo for this issue, if not, please point me in the right direction.

When installing `ros-dashing-desktop` through the DEB packages (`sudo apt install ros-dashing-desktop`) it seems to leave out the cli package for actions. You have to do an additional `sudo apt install ros-dashing-ros2action`.

Not sure where this is configured, if someone wants to point me in the right direction I can try to fix and create a PR.

Thanks

**Comment by sloretz** [comment]
Mind making a PR to ros2/variants? The spot is here: https://github.com/ros2/variants/blob/0b5daaacf36c89c8edb65119b8125f72ba4a820b/ros_core/package.xml#L50-L62

**Comment by slessans** [comment]
Thank you for pointing me to that. I will make a PR sometime this evening.
