### ISSUE TITLE
False positive clang warning with braced initializer

### ISSUE THREAD

**Issue by rotu** [ros2/ci#357]
On OS X, clang throws an erroneous warning  for this correct code:

https://github.com/RoverRobotics-forks/rmw_cyclonedds/blob/a850bec48226b832db469c48c9da32e170bffbf0/rmw_cyclonedds_cpp/src/Serialization.cpp#L291

https://ci.ros2.org/job/ci_osx/7277/warnings11Result/new/

**Comment by dirk-thomas** [comment]
Reference to the ticket where this came up: https://github.com/ros2/rmw_cyclonedds/pull/80#issuecomment-565184037

@rotu What is the goal / acceptance criteria of this ticket? I would guess `clang` would need to fix this false positive warning. If that is the case please close the ticket since that is not in the scope of this repository. Maybe consider create a ticket upstream for clang?

**Comment by rotu** [comment]
The goal is to modify CI to turn off or whitelist the warning. This is already fixed in more recent Clang  versions: https://bugs.llvm.org/show_bug.cgi?id=21629

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for the proposal. If this had been addressed upstream and also can be worked around by code I don't think we will be spending resources in this.

**Comment by rotu** [comment]
I don’t know if I understand CI enough to do the PR. This also might be related to using the obsolete warnings plugin (#315). I don’t know why a build warning should cause CI to fail when we have dedicated linters for those checks.

**Comment by dirk-thomas** [comment]
A build warning does not fail the Jenkins build - it only marks it as unstable (in order to distinguish it from all green builds). Only the GitHub status API doesn't support a tri state and considers unstable the same as a failed build.

**Comment by clalancette** [comment]
I'm pretty sure this hasn't been a problem in a while (we have had green macOS jobs for a while).  So I'm closing this out, but feel free to reopen if you still see a problem here.
