### ISSUE TITLE
Transition Windows/Mac CI farms to cloud virtualization

### ISSUE THREAD

**Issue by brawner** [ros2/ci#365]
This issue tracks the progress of transitioning the Windows CI/Mac CI machines to cloud virtualization. The goal of the project is to create a more reproducible, deployable and scalable Jenkins CI farm. Because Microsoft has embraced containerization in the last couple of years, it is feasible to run Windows CI instances inside docker containers running on VMs from a cloud provider. On the mac side, MacStadium offers potential for virtualization with mac instances.

Window cloud virtualization tasks:
- [x]  Demonstrate a CI build by running run_ros2_batch.py from a docker container 
- [x]  Deploy a Jenkin's build job to an EC2 instance
    https://citest.ros2.org/job/ci_windows/87/
- [x]  Merge windows_docker_resources PR (https://github.com/ros2/ci/pull/361) (1/31/2019)
- [x]  Cloud Jenkins agents running side-by-side with current CI farm (1/31/2019)
- [x]  Windows configuration management of EC2 VMs with Chef (1/31/2019)
- [x]  Retire bare metal CI Windows servers (3/1/2019)

Mac Cloud Virtualization tasks (TBD)
- [ ]  Investigate MacStadium's cloud virtualization offering
- [ ]  Demostrate CI build by running run_ros2_batch.py from virtual mac instance
- [ ]  Deploy a Jenkin's build job to a MacStadium instance
- [ ]  Create and Merge Mac CI PR
- [ ]  Cloud Jenkins agents running side-by-side with current CI farm
- [ ]  Mac configuration management of MacStadium VMs with Orka
- [ ]  Retire bare metal CI Mac servers

**Comment by brawner** [comment]
I've run into an issue attempting to build in a directory mounted with `docker run -v`. When building, cmake runs a compiler check on a simple program in debug mode and with the `/Zi` build flag. This creates a pdb file with debug symbols. Any references to the debug symbols are requested through mspdbsrv.exe. I suspect this has to do with file handle access across the mounted directory, between the containerized OS and the host OS. Building in a directory that's not in a mounted location, but copying build/install results back to the mounted directory seems to work.

Example of output failure.
```
cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Z
c:forScope /Zc:inline /Fo"cmTC_c31aa.dir\Debug\\" /Fd"cmTC_c31aa.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue C:\TEMP\workdir\ws\build\poco_vendor\CMakeFiles\CMakeTmp
\testCCompiler.c
[19.406s]
[19.406s]       testCCompiler.c
[19.406s]     LINK : fatal error LNK1318: Unexpected PDB error; RPC (23) '(0x000006E7)' [C:\TEMP\workdir\ws\build\poco_vendor\CMakeFiles\CMakeTmp\cmTC_c31aa.vcxproj]
```

**Comment by brawner** [comment]
To run a containerized Windows OS on Windows, the containerized OS has compatibility requirements with the host OS. See https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-1909%2Cwindows-10-1909

This means that without Hyper-V enabled, the containerized OS must match the host OS. With Hyper-V, it generally means the Release Id of the OS of the container must the same _or older_ than the host OS. I've added logic in my PR for the Release ID to be passed into the docker image when building on a jenkins job.

However, this also means that if someone downloads the image from the cloud instance to run on their own machine, they will have to run a matching Release Id of the cloud instance, or one compatible through Hyper-V.

**Comment by brawner** [comment]
Currently, it is not possible to install RTI Connext through the command line on Windows. The installer provides a headless mode and a text-based mode. Unfortunately, the headless mode is not available for the evaluation installer, and the text-base mode is not available on Windows.

https://community.rti.com/static/documentation/connext-dds/5.2.0/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_GettingStarted/Content/GettingStarted/Installing_ConnextDDS.htm

**Comment by ivanpauno** [comment]
@brawner I assigned you in order to avoid the issue appearing again in our triagging process.
Feel free to unassing yourself if you think that the assignment is wrong.

**Comment by brawner** [comment]
Thanks to @cottsay (https://github.com/brawner/ci/pull/1), PR #361 now has Connext functionality. He added a git submodule pointing to a private OSRF repo to download a professional Connext installer. The professional installer can be installed headless in a docker container, which was not possible with the evaluation installer.

**Comment by brawner** [comment]
ci_windows and ci_windows-container testing differences:

Turtlesim incompatible with Qt 5.12.7
* ci_indows 9157 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9157)](http://ci.ros2.org/job/ci_windows/9157/) ci_windows-container 39 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=39)](http://ci.ros2.org/job/ci_windows-container/39/)
* ci_windows 9133 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9133)](http://ci.ros2.org/job/ci_windows/9133/) ci_windows-container 14 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=14)](http://ci.ros2.org/job/ci_windows-container/14/)

Caught MSBuild warnings in newer versions of Visual Studio 
* ci_windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9156)](http://ci.ros2.org/job/ci_windows/9156/) ci_windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=38)](http://ci.ros2.org/job/ci_windows-container/38/)

Timing related flakiness
* ci_windows 9150 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9150)](http://ci.ros2.org/job/ci_windows/9150/) ci_windows-container 32 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=32)](http://ci.ros2.org/job/ci_windows-container/32/)
* ci_windows 9146 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9146)](http://ci.ros2.org/job/ci_windows/9146/) ci_windows-container 26 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=26)](http://ci.ros2.org/job/ci_windows-container/26/)
* ci_windows 9132 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9132)](http://ci.ros2.org/job/ci_windows/9132/) ci_windows-container 13 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=13)](http://ci.ros2.org/job/ci_windows-container/13/)

A lot of failed tests, hard to tell which ones were different
* ci_windows 9130 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9130)](http://ci.ros2.org/job/ci_windows/9130/) ci_windows-container 12 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=12)](http://ci.ros2.org/job/ci_windows-container/12/)

ci_windows failed tests, ci_windows-container succeeded at
* ci_windows 9123 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9123)](http://ci.ros2.org/job/ci_windows/9123/) ci_windows-container 9[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=9)](http://ci.ros2.org/job/ci_windows-container/9/)

**Comment by brawner** [comment]
# ci_windows build failures
*  ci_windows 9360 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9360)](https://ci.ros2.org/job/ci_windows/9360/)  ci_windows-container 208 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=208)](https://ci.ros2.org/job/ci_windows-container/208/)
*  ci_windows 9359 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9359)](https://ci.ros2.org/job/ci_windows/9359/)  ci_windows-container 207 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=207)](https://ci.ros2.org/job/ci_windows-container/207/)
*  ci_windows 9335 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9335)](https://ci.ros2.org/job/ci_windows/9335/)  ci_windows-container 192 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=192)](https://ci.ros2.org/job/ci_windows-container/192/)
*  ci_windows 9334 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9334)](https://ci.ros2.org/job/ci_windows/9334/)  ci_windows-container 191 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=191)](https://ci.ros2.org/job/ci_windows-container/191/)
*  ci_windows 9333 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9333)](https://ci.ros2.org/job/ci_windows/9333/)  ci_windows-container 190 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=190)](https://ci.ros2.org/job/ci_windows-container/190/)
*  ci_windows 9332 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9332)](https://ci.ros2.org/job/ci_windows/9332/)  ci_windows-container 189 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=189)](https://ci.ros2.org/job/ci_windows-container/189/)
*  ci_windows 9319 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9319)](https://ci.ros2.org/job/ci_windows/9319/)  ci_windows-container 179 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=179)](https://ci.ros2.org/job/ci_windows-container/179/)
*  ci_windows 9318 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9318)](https://ci.ros2.org/job/ci_windows/9318/)  ci_windows-container 178 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=178)](https://ci.ros2.org/job/ci_windows-container/178/)
*  ci_windows 9294 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9294)](https://ci.ros2.org/job/ci_windows/9294/)  ci_windows-container 157 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=157)](https://ci.ros2.org/job/ci_windows-container/157/)
*  ci_windows 9288 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9288)](https://ci.ros2.org/job/ci_windows/9288/)  ci_windows-container 156 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=156)](https://ci.ros2.org/job/ci_windows-container/156/)
*  ci_windows 9286 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9286)](https://ci.ros2.org/job/ci_windows/9286/)  ci_windows-container 153 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=153)](https://ci.ros2.org/job/ci_windows-container/153/)
*  ci_windows 9285 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9285)](https://ci.ros2.org/job/ci_windows/9285/)  ci_windows-container 152 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=152)](https://ci.ros2.org/job/ci_windows-container/152/)
*  ci_windows 9284 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9284)](https://ci.ros2.org/job/ci_windows/9284/)  ci_windows-container 151 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=151)](https://ci.ros2.org/job/ci_windows-container/151/)
*  ci_windows 9283 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9283)](https://ci.ros2.org/job/ci_windows/9283/)  ci_windows-container 150 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=150)](https://ci.ros2.org/job/ci_windows-container/150/)
*  ci_windows 9282 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9282)](https://ci.ros2.org/job/ci_windows/9282/)  ci_windows-container 149 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=149)](https://ci.ros2.org/job/ci_windows-container/149/)
*  ci_windows 9277 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9277)](https://ci.ros2.org/job/ci_windows/9277/)  ci_windows-container 144 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=144)](https://ci.ros2.org/job/ci_windows-container/144/)
*  ci_windows 9275 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9275)](https://ci.ros2.org/job/ci_windows/9275/)  ci_windows-container 142 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=142)](https://ci.ros2.org/job/ci_windows-container/142/)
*  ci_windows 9261 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9261)](https://ci.ros2.org/job/ci_windows/9261/)  ci_windows-container 130 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=130)](https://ci.ros2.org/job/ci_windows-container/130/)
*  ci_windows 9255 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9255)](https://ci.ros2.org/job/ci_windows/9255/)  ci_windows-container 127 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=127)](https://ci.ros2.org/job/ci_windows-container/127/)
*  ci_windows 9249 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9249)](https://ci.ros2.org/job/ci_windows/9249/)  ci_windows-container 123 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=123)](https://ci.ros2.org/job/ci_windows-container/123/)
*  ci_windows 9248 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9248)](https://ci.ros2.org/job/ci_windows/9248/)  ci_windows-container 122 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=122)](https://ci.ros2.org/job/ci_windows-container/122/)
*  ci_windows 9247 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9247)](https://ci.ros2.org/job/ci_windows/9247/)  ci_windows-container 121 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=121)](https://ci.ros2.org/job/ci_windows-container/121/)
*  ci_windows 9198 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9198)](https://ci.ros2.org/job/ci_windows/9198/)  ci_windows-container 84 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=84)](https://ci.ros2.org/job/ci_windows-container/84/)
*  ci_windows 9112 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9112)](https://ci.ros2.org/job/ci_windows/9112/)  ci_windows-container 4 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=4)](https://ci.ros2.org/job/ci_windows-container/4/)

**Comment by brawner** [comment]
# ci_windows-container build failures
*  ci_windows 9219 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9219)](https://ci.ros2.org/job/ci_windows/9219/)  ci_windows-container 103 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=103)](https://ci.ros2.org/job/ci_windows-container/103/)
*  ci_windows 9216 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9216)](https://ci.ros2.org/job/ci_windows/9216/)  ci_windows-container 100 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=100)](https://ci.ros2.org/job/ci_windows-container/100/)
*  ci_windows 9203 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9203)](https://ci.ros2.org/job/ci_windows/9203/)  ci_windows-container 88 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=88)](https://ci.ros2.org/job/ci_windows-container/88/)
*  ci_windows 9192 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9192)](https://ci.ros2.org/job/ci_windows/9192/)  ci_windows-container 75 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=75)](https://ci.ros2.org/job/ci_windows-container/75/)
*  ci_windows 9190 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9190)](https://ci.ros2.org/job/ci_windows/9190/)  ci_windows-container 73 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=73)](https://ci.ros2.org/job/ci_windows-container/73/)
*  ci_windows 9184 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9184)](https://ci.ros2.org/job/ci_windows/9184/)  ci_windows-container 58 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=58)](https://ci.ros2.org/job/ci_windows-container/58/)
*  ci_windows 9181 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9181)](https://ci.ros2.org/job/ci_windows/9181/)  ci_windows-container 55 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=55)](https://ci.ros2.org/job/ci_windows-container/55/)
*  ci_windows 9157 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9157)](https://ci.ros2.org/job/ci_windows/9157/)  ci_windows-container 39 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=39)](https://ci.ros2.org/job/ci_windows-container/39/)
*  ci_windows 9133 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9133)](https://ci.ros2.org/job/ci_windows/9133/)  ci_windows-container 14 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=14)](https://ci.ros2.org/job/ci_windows-container/14/)

**Comment by brawner** [comment]
@nuclearsandwich Can this be closed in favor of new MacOS investigations?
