### ISSUE TITLE
Daily invalidation of dockerfiles isn't working

### ISSUE THREAD

**Issue by dhood** [ros2/ci#37]
We are using `RUN echo "@today_str"` [in our Dockerfile](https://github.com/ros2/ci/blob/b1d13b11ab1b6c287b72e9b67346326630d2bac4/linux_docker_resources/Dockerfile#L87) to invalidate it daily, but unlike the dockerfiles in the ros1 buildfarm (e.g. [this one](https://github.com/ros-infrastructure/ros_buildfarm/blob/20844f070abe188fc492f7f2db227462b06a161b/ros_buildfarm/templates/release/binarydeb_install_task.Dockerfile.em#L50)), the dockerfile in the ros2 buildfarm is not an empy template. 

As a result we just end up printing the string (from http://ci.ros2.org/job/ci_turtlebot-demo/3/consoleFull):

```
17:12:55 Step 40 : RUN echo "@today_str"
17:12:55  ---> Running in 7e19d30c09ba
17:12:55 @today_str
```
and then using the image from the cache on all successive builds (from http://ci.ros2.org/view/packaging/job/packaging_linux/611/consoleFull): 

```
14:05:04 Step 39 : RUN echo "@today_str"
14:05:04  ---> Using cache
14:05:04  ---> 701834003880
```

**Comment by nuclearsandwich** [comment]
Since there's some additional impetus to use a template-ized Dockerfile for #35 (See https://github.com/ros2/ci/pull/35#pullrequestreview-26962079). I could work on this change either as a dependent PR of #35 or as a followup once it merges.

**Comment by dhood** [comment]
No need to hold up #35 for this, it is just something we should get to at some point.
