### ISSUE TITLE
RTI Connext and BuildTools 16.5 incompatibilty bug

### ISSUE THREAD

**Issue by brawner** [ros2/ci#411]
There is a unusual incompatibility with the latest MS VS BuildTools version (16.5) and RTI Connext. I'm still investigating, but 16.4.5 works fine.

Example failure
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9557)](https://ci.ros2.org/job/ci_windows/9557/)

**Comment by brawner** [comment]
New PR to address this issue https://github.com/ros2/rosidl_typesupport_connext/pull/46

**Comment by dirk-thomas** [comment]
@brawner Please unpin the Visual Studio - reverting #410.

**Comment by brawner** [comment]
Just merged this one https://github.com/ros2/ci/pull/412
