### ISSUE TITLE
Dockerfile.msvc2019: spurious escape character?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros2/ci#420]
As I'm not entirely comfortable with Docker on Windows, I may have misinterpreted things, but is the backtick at the end of line 133 in `Dockerfile.msvc2019` supposed to be there?

https://github.com/ros2/ci/blob/3ec2369bd0ddc04e80b9fadab272abcd46e08b64/windows_docker_resources/Dockerfile.msvc2019#L133-L134

**Comment by cottsay** [comment]
The escape character is configured to be a backtick at the top of the file: https://github.com/ros2/ci/blob/3ec2369bd0ddc04e80b9fadab272abcd46e08b64/windows_docker_resources/Dockerfile.msvc2019#L1

Here are the docs: https://docs.docker.com/engine/reference/builder/#escape

**Comment by cottsay** [comment]
Oh, I see, you're talking about the one at the end of the comment. That does seem like a problem. @brawner, can you confirm?

**Comment by brawner** [comment]
Since the default escape character in dockerfiles is `\`, it becomes an issue for windows paths in dockerfiles. Using the backtick is the other recommended option.

https://docs.docker.com/engine/reference/builder/#escape#escape

**Comment by brawner** [comment]
Err, I made the same mistake. I think that backtick can probably be removed.

**Comment by gavanderhoorn** [comment]
Thanks for explaining it to me twice, but I do understand the concept of an escape character ;)

My question was indeed about the escape character at the end of that comment, which seems to suggest the next line is actually never executed? Or is that not how this is supposed to work?

**Comment by brawner** [comment]
Yah, I'm sorry about that. I changed my response after reading more closely. 

The line most definitely executes as BuildTools is correctly downloaded and installed. It looks like the escape character is ignored as part of a comment.

**Comment by gavanderhoorn** [comment]
So in the end, is this a problem, or should I close the issue?

**Comment by brawner** [comment]
Yes, I believe this issue has been resolved. The dockerfile was significantly redone as part of https://github.com/ros2/ci/pull/425
