### ISSUE TITLE
Some Windows builds succeed or get marked as unstable even though they fail

### ISSUE THREAD

**Issue by brawner** [ros2/ci#433]
This may have already been resolved by #428, but I wanted to track it just in case. This `ci_windows` job was a complete failure, yet it was marked successful by Jenkins. @nuclearsandwich, when you have updated the jenkins nodes, I'll rerun it to test this out.

**Comment by brawner** [comment]
Err, actually it was this one.
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10091)](https://ci.ros2.org/job/ci_windows/10091/)

**Comment by hidmic** [comment]
@nuclearsandwich has that nodes update happened already?

**Comment by brawner** [comment]
We found out that %errorlevel% in `|| exit /b %errorlevel%` (#428) was being expanded when the ci_job script was being read, which led to builds saying success. We just fixed that in (#438).

**Comment by brawner** [comment]
I believe this has been addressed by #428 and #438. If this comes up again we can reopen this issue.
