### ISSUE TITLE
Builds selecting CI_USE_FASTRTPS_DYNAMIC but not CI_USE_FASTRTPS_STATIC fail

### ISSUE THREAD

**Issue by ivanpauno** [ros2/ci#449]
If `CI_USE_FASTRTPS_DYNAMIC` is ticked and `CI_USE_FASTRTPS_STATIC` is not, the build will fail. See:

* https://ci.ros2.org/job/ci_linux/10725/

The failure is because of the build ignoring `rosidl_typesupport_fastrtps_*` packages:

<details>
<summary>output</summary>

```
# BEGIN SUBSECTION: ignored packages
16:40:00 Trying to ignore the following packages:
16:40:00 - actionlib_msgs
16:40:00 - common_interfaces
16:40:00 - cv_bridge
16:40:00 - opencv_tests
16:40:00 - ros1_bridge
16:40:00 - shape_msgs
16:40:00 - stereo_msgs
16:40:00 - vision_opencv
16:40:00 - rmw_connext_cpp
16:40:00 - rosidl_typesupport_connext_c
16:40:00 - rosidl_typesupport_connext_cpp
16:40:00 - connext_cmake_module
16:40:00 - rmw_connext_shared_cpp
16:40:00 - cyclonedds
16:40:00 - cyclonedds_cmake_module
16:40:00 - rmw_cyclonedds_cpp
16:40:00 - rmw_fastrtps_cpp
16:40:00 - rosidl_typesupport_fastrtps_c
16:40:00 - rosidl_typesupport_fastrtps_cpp
16:40:00 - opensplice_cmake_module
16:40:00 - rmw_opensplice_cpp
16:40:00 - rosidl_typesupport_opensplice_c
16:40:00 - rosidl_typesupport_opensplice_cpp

```

</details>

when they are actually required https://github.com/ros2/rmw_fastrtps/blob/98d14729df0aa6d1ce01d7165d91e7cee257dd5c/rmw_fastrtps_dynamic_cpp/package.xml#L27-L28.

P.S.: There's no need to fix this if https://github.com/ros2/rmw_fastrtps/issues/382 is addressed.

**Comment by sloretz** [comment]
> P.S.: There's no need to fix this if ros2/rmw_fastrtps#382 is addressed.

Closing in favor of  ros2/rmw_fastrtps#382 as discussed in today's meeting.
