### ISSUE TITLE
add parameters to dockerfile, avoid the requirement of rti submodule.

### ISSUE THREAD

**Issue by sunbo57123** [ros2/ci#458]
hi,

I'm trying to build CI on ARM/AMD servers, and Jenkins can't pull submodules related with rti. This may be caused by private repo of rti license. RTI connext is an option for dds implementations, so it is possible to build jobs without using rti.

so, what about:

pass the parameters to the Dockerfile, so if I choose `CI_USE_CONNEXT_STATIC` as False, the rti-related operations will not be performed automatically.

**Comment by nuclearsandwich** [comment]
> pass the parameters to the Dockerfile, so if I choose `CI_USE_CONNEXT_STATIC` as False, the rti-related operations will not be performed automatically.

If you would contribute a PR which implements this behavior we would review it. I think one initial concern I have is the effect the conditional installation will have on Docker layer caching.

**Comment by clalancette** [comment]
Given the age of this, I'm going to close it out.  If you'd still like to contribute this, please feel free to reopen or open a pull request directly.
