### ISSUE TITLE
Revert MSVS version pin from PR #462

### ISSUE THREAD

**Issue by brawner** [ros2/ci#463]
There was an upstream issue with the most recent versions of MS BuildTools v16.6.1/16.6.0, where building the netifaces wheel failed during a pip upgrade. It seems to be a very recent issue as described [here](https://developercommunity.visualstudio.com/content/problem/1060913/1661-a-package-is-not-found-for-download-no-more-6.html). 

Once it has been resolved, the windows CI dockerfiles should switch back to downloading the most recent releases.

Followup to #462

**Comment by dirk-thomas** [comment]
@brawner Can this be closed with #465 merged?
