### ISSUE TITLE
Error in ros2_batch_job due to pytest being imported before install.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ci#467]
Windows and macOS nightlies are failing after https://github.com/ros2/ci/pull/415/ because pytest is installed as a pip dependency during the batch job. 

The failure is not present on Linux because pytest is installed as an apt dependency of python3-pytest-mock: https://github.com/ros2/ci/blob/3f57d6d61488743d9cff27c53f89f4a2daffdf82/linux_docker_resources/Dockerfile#L62

**Comment by j-rivero** [comment]
Does it make sense to move the import statement just before using it in the code? Should be a simple fix if it does not bring undesired side effects. I'll test that and send a new PR if it goes well.

**Comment by nuclearsandwich** [comment]
Since we are reverting #469 this issue is open again. It is worth stressing that any solution which relies on the pytest version outside the venv matching the version inside is incomplete without enforcing that on all platforms and in all situations where a venv is used.

**Comment by clalancette** [comment]
I think we've removed everything having to do with this problem, so I'll go ahead and close this.  Feel free to reopen if I'm mistaken.
