### ISSUE TITLE
False positive Clang warnings on Linux from openssl output.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ci#473]
Lines such as

```
258: validate_local_permissions failed: (127) Failed to parse PKCS7 SMIME document: 281473198688096:error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:../crypto/pkcs7/pk7_smime.c:284:Verify error:self signed certificate
```

from cyclonedds security tests are matching the [Jenkins analysis model regexp](https://github.com/jenkinsci/analysis-model/blob/ccc7d876160b5c610e62e103de08715e9609cada/src/main/java/edu/hm/hafner/analysis/parser/ClangParser.java#L20-L21) as a Clang warning.

[Linux aarch64 debug #1234](https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1234/clang/) is an example build exhibiting these warnings.

I've done some quick checking to see if there's a described format for clang messages in order to improve upstream's regexp and haven't found anything yet. Since our normal Linux builds use GCC we don't necessarily need to look at them for Clang errors so I'm going to open a PR that adds that parser only conditionally.

This is related to https://github.com/ros2/ci/issues/316

**Comment by dirk-thomas** [comment]
> Since our normal Linux builds use GCC we don't necessarily need to look at them for Clang errors so I'm going to open a PR that adds that parser only conditionally.

Since the option to use `clang` is a job parameter I am not sure how the parser could be conditional based on that parameter?

**Comment by nuclearsandwich** [comment]
> Since the option to use `clang` is a job parameter I am not sure how the parser could be conditional based on that parameter?

Yep I realized that trying to set it up. Doing it based on the job default would take away the ability to see clang warnings on regular Linux CI jobs. So I don't currently have a solution to this problem.

**Comment by dirk-thomas** [comment]
Since we have to resolve #316 soon anyway in order to get the CI to be green I would say it is fine to wait for that.
