### ISSUE TITLE
"The system cannot find the path specified." for every command invoked during a Windows build

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ci#495]
Every invocation of the `env.bat` file prints the following error message before running the command passed to it as arguments. See e.g. https://ci.ros2.org/view/nightly/job/nightly_win_deb/1682/consoleFull#console-section-5

```
# BEGIN SUBSECTION: build
==> env.bat C:\Python38\Scripts\colcon.EXE build --base-paths "src" --build-base "build" --install-base "install" --merge-install --event-handlers console_cohesion+ console_package_list+ --cmake-args -DBUILD_TESTING=ON --no-warn-unused-cli -DCMAKE_BUILD_TYPE=Debug -DINSTALL_EXAMPLES=OFF -DSECURITY=ON
The system cannot find the path specified.
###############################################################################

         (c) Copyright, Real-Time Innovations, All rights reserved.            

                           RTI Connext DDS 5.3.1                     

###############################################################################
Topological order
...
```

The actual `colcon` command is executed just fine. Also the command run before (setting up RTI Connext) executes just fine. Therefore I suspect that one of the entries in `PATH` is invalid.

The only other command invoked before setting up Connext is https://github.com/ros2/ci/blob/6bb484203ee63cbbfcfee1e76a8441e954837e84/ros2_batch_job/windows_batch/__init__.py#L71-L74 but then I would expect the whole build to fail.

**Comment by clalancette** [comment]
As far as I can tell, this is no longer an issue.  So I'll close this out.
