### ISSUE TITLE
publish xUnit test result report failed in ros2 ci

### ISSUE THREAD

**Issue by flynneva** [ros2/ci#505]
[see it here for the grbl_ros ROS2 package.](http://build.ros2.org/job/Fdev__grbl_ros__ubuntu_focal_amd64/8/console)

looks like the build & test went fine but the publishing of the report failed, causing the ci to fail.

i noticed the most recent commit to this repo says something about junit....does that fix this issue?

```
16:39:22 ERROR: Step ‘Publish xUnit test result report’ failed:
    The result file '/home/jenkins-agent/workspace/Fdev__grbl_ros__ubuntu_focal_amd64/ws/
    test_results/grbl_ros/pytest.xml' for the metric 'JUnit' is not valid.
    The result file has been skipped.
```

**Comment by dirk-thomas** [comment]
For Focal and older distros this issue has been address by ros-infrastructure/ros_buildfarm#836 - see the latest build: [![Build Status](http://build.ros2.org/buildStatus/icon?job=Fdev__grbl_ros__ubuntu_focal_amd64&build=10)](http://build.ros2.org/job/Fdev__grbl_ros__ubuntu_focal_amd64/10/)

It seems like you repository hasn't been added to Rolling yet. For that I would expect that you package needs a patch similar to ros2/rclpy#587.
