### ISSUE TITLE
About https://build.ros2.org/ Jenkins's "Collapsing Console Sections" setting

### ISSUE THREAD

**Issue by samlin0419** [ros2/ci#577]
Dear Sir,

Could you help me to set the Jenkins's "Collapsing Console Sections" setting ?

Because my [**console section** are not aligned and my **section name** always the same, please see the attached screen.

![image](https://user-images.githubusercontent.com/39365777/119432360-cd9e5c00-bd46-11eb-94b3-98d3c76c7098.png)

![image](https://user-images.githubusercontent.com/39365777/119432532-1229f780-bd47-11eb-8c9b-943926fa8c69.png)

Thanks a lot!

Sam

**Comment by clalancette** [comment]
This doesn't seem to have anything to do with ROS 2 CI.  As such, I'm going to close this out.  If you do have an issue with the ROS 2 CI, please open another issue and give us a lot of details about exactly what you are trying to do that is not working.

**Comment by samlin0419** [comment]
> This doesn't seem to have anything to do with ROS 2 CI. As such, I'm going to close this out. If you do have an issue with the ROS 2 CI, please open another issue and give us a lot of details about exactly what you are trying to do that is not working.

Dear Sir,

Okay, thanks for your helping.

Best regards,
Sam
