### ISSUE TITLE
Connext incorrectly trying to be installed in RHEL packaging job for Foxy

### ISSUE THREAD

**Issue by jacobperron** [ros2/ci#590]
For some reason when we set the rosdistro to `foxy`, the packaging job attempts to install Connext and fails to build, e.g. https://ci.ros2.org/view/All/job/ci_linux-rhel/148/

```
17:45:05 Installing Connext...
17:45:05 Installing Connext binaries off RTI website...
17:45:05 python3: can't open file '/tmp/rti_web_binaries_install_script.py': [Errno 2] No such file or directory
17:45:06 Connext not installed correctly (maybe you're on an ARM machine?).
```

If we change the rosdistro to `rolling`, the build proceeds as expected.

I haven't tried other distros like `galactic`.

**Comment by clalancette** [comment]
I just retried this on https://ci.ros2.org/job/ci_linux-rhel/154/ , and the issue doesn't seem to be there.  There have been a number of changes to the CI code of late, including removal of Dashing (https://github.com/ros2/ci/pull/580), removal of Opensplice (https://github.com/ros2/ci/pull/582), and enabling RTI on RHEL (https://github.com/ros2/ci/pull/594).  I suspect that one of those fixed this issue, so I'm going to go ahead and close it.  Feel free to reopen if you see it again.
