### ISSUE TITLE
rticonnextdds-src

### ISSUE THREAD

**Issue by bsamadi** [ros2/ci#591]
Does the rticonnextdds-src repository exist? It does not seem to be open to the public. I cannot update (clone) the submodules of this repo.

**Comment by aprotyas** [comment]
I believe that's closed source.

**Comment by aprotyas** [comment]
@bsamadi depending on your use-case, this might be relevant from the README:

> Another thing to check is the credentials settings. The RTI binaries are provided by a git submodule which points to a private GitHub repository. You'll need to setup at least one ssh key in the Jenkins Credentials plugin and add the public part of that key as a deploy key on the private GitHub repository, currently https://github.com/osrf/rticonnextdds-src. Then on each job you'll want to make sure that this key is selected in two places. First under the 'Source Code Management' section, there is a 'Credentials' drop down box under the 'Repositories' section. Select the appropriate ssh key from that list. Second, under the 'SSH Agent' option, select the same ssh key from the drop down list called 'Credentials'. Note this option will not be there for Windows because I could not get the ssh-agent to work on Windows correctly and it is not needed anyways.

**Comment by bsamadi** [comment]
Thank you @aprotyas. I don't have access to this repository: [https://github.com/osrf/rticonnextdds-src](https://github.com/osrf/rticonnextdds-src). I therefore can't have an SSH key with access to this repository. 

I am a little bit surprised. Do you if this private repository is needed for ROS Galactic?

**Comment by aprotyas** [comment]
> Do you if this private repository is needed for ROS Galactic?

Sorry, I don't have a solid answer for that. You won't be able to run tests with Connext DDS, for one, but I can't say more than that.

In terms of running ROS 2 Galactic out of the box, the default middleware is Cyclone DDS.
