### ISSUE TITLE
Retry nightlies on a different node if jobs fail because of setup issues

### ISSUE THREAD

**Issue by dhood** [ros2/ci#6]
Sometimes nightly jobs fail because of setup issues, such as issues with Docker (e.g. [nightly_linux_repeated 448](http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/448/console)) or Jenkins (e.g. [nightly osx release 241](http://ci.ros2.org/view/nightly/job/nightly_osx_release/241/console)). Currently we will notice these failures in the morning, take the failing nodes offline, and (maybe) re-run the jobs on another node during the day.

It would be handy if when jobs fail because of setup issues, the job is retried on another node automatically. In the case of the nightlies, it will save us from having to use the remaining online nodes for running nightly jobs during the daytime when we would probably prefer to use them for CI.

**Comment by mikaelarguedas** [comment]
As per offline discussion on 11/8 this should not happen because all nodes should have the exact same configuration and broken nodes should be offline and investigated.
