### ISSUE TITLE
CI is broken because osrf/rticonnextdds-src doesn't exist anymore?

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ci#601]
e.g. https://ci.ros2.org/job/ci_windows/15905/console

Fails on the step trying to clone submodules in https://github.com/ros2/ci/tree/master/linux_docker_resources

But https://github.com/osrf/rticonnextdds-src is 404. Did you delete the repo and accidentally leave the references to it?

**Comment by clalancette** [comment]
No, I don't think so.  It looks like the Windows nodes are having connectivity issues somehow.

**Comment by aprotyas** [comment]
> No, I don't think so. It looks like the Windows nodes are having connectivity issues somehow.

Yes, re-running the CI jobs has worked over the last few days. Also, I believe osrf/rticonnextdds-src is closed source anyway so we couldn't tell if it's deleted or not.

**Comment by emersonknapp** [comment]
Oh - good point that it's private. That makes sense. Guess it was some GitHub tokens connectivity stuff... I'll close this - after 2 failed builds now it's running again :shrug:
