### ISSUE TITLE
libasio-dev recommended packages installed?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ci#61]
I noticed in http://ci.ros2.org/job/ci_linux/2476/consoleFull (step 32) that all the recommended packages for libasio-dev were installed. Is this the expected behavior?

[apt command ran](https://github.com/ros2/ci/blob/817dcbbf81f09ff629c61e4cfa364ce6724d8317/linux_docker_resources/Dockerfile#L68):
```
Step 32 : RUN apt-get update && apt-get install -y libasio-dev libtinyxml2-dev valgrind libssl-dev
```
resulting installed packages:
```
  gdb gdbserver icu-devtools libbabeltrace-ctf1 libbabeltrace1
  libboost-date-time-dev libboost-date-time1.58-dev libboost-date-time1.58.0
  libboost-dev libboost-regex-dev libboost-regex1.58-dev libboost-regex1.58.0
  libboost-serialization1.58-dev libboost-serialization1.58.0 libboost1.58-dev
  libc6-dbg libicu-dev libssl-doc zlib1g-dev
```

AFAICT all these boost packages are [recommended by libasio-dev](http://packages.ubuntu.com/xenial/libasio-dev) but not required by any package.

**Comment by tfoote** [comment]
Apt installs recommends by default. We should probably use `--no-install-recommends`
