### ISSUE TITLE
Add/change turtlebot demo to build on aarch64

### ISSUE THREAD

**Issue by clalancette** [ros2/ci#69]
The current turtlebot_demo CI job runs on labels marked as "linux", which in our build farm is implicitly x86_64 machines. However, the real turtlebot demo is almost certainly going to run on aarch64, so we should either change the label on the turtlebot-demo job to be "linux_aarch64", or we should add an additional job to build turtlebot-demo on both architectures. @nuclearsandwich @gerkey does that make sense?

**Comment by gerkey** [comment]
I like the idea of adding a second job labeled `linux_aarch64`. Then we can rest assured that it builds on both architectures.

**Comment by mikaelarguedas** [comment]
:+1: for creating another job "ci_turtlebot-demo-aarch64" rather than modifying the label of the existing one

**Comment by gerkey** [comment]
I'll do this.

**Comment by gerkey** [comment]
Fixed by #70.
