### ISSUE TITLE
What is the best place to add build argument to packaging job?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ci#83]
Hey guys, I'd like the Security feature to be part of the packaging jobs so that people can try it out from "binaries" on every platform. The packaging jobs don't take "ament build" parameters. What is the best thing to do here ? add a parameter also available from the UI? or add tham manually in the packaging job template?

Thamks!

**Comment by dirk-thomas** [comment]
Exposing the ament build parameters as a parameter of the Jenkins job would be more flexible (and is already done for the other jobs).

**Comment by wjwwood** [comment]
Does https://github.com/ros2/ci/pull/84 close this?

**Comment by mikaelarguedas** [comment]
Absolutely, thanks for the reminder
