### ISSUE TITLE
nightly linux coverage job failing due to malformed arguments

### ISSUE THREAD

**Issue by wjwwood** [ros2/ci#85]
```
07:31:48 CMake Error: The source directory "/home/rosbuild/ci_scripts/ws/build/ament_cmake_core/--ament-cmake-args" does not exist.
07:31:48 Specify --help for usage, or press the help button on the CMake GUI.
```

-- http://ci.ros2.org/view/nightly/job/nightly_linux_coverage/417/console

Which is obviously not right. I'm not sure why this is yet, but if anyone knows off hand, I'd appreciate the nod in the right direction.

**Comment by mikaelarguedas** [comment]
I think that's related to https://github.com/ros2/ci/issues/51. Mu guess is that `-DSECURITY=ON` doesnt get it's end delimiter and thus the next argument gets merged into it

**Comment by wjwwood** [comment]
> I think that's related to #51. Mu guess is that -DSECURITY=ON doesnt get it's end delimiter and thus the next argument gets merged into it

I was just getting to the same conclusion, but do you know why that is? (i.e. is it something you know how to fix off-hand, or should I dig into it?)

**Comment by mikaelarguedas** [comment]
Not sure what the right fix is, I didn't have time to investigate. My guess is that the logic in https://github.com/ros2/ci/blob/master/job_templates/ci_job.xml.em#L152-L173 and it's windows equivalent is fragile, and that the check for the end delimiter should be done either in a different place (make sure we don't append anything else to that list) or in a smarter way (identifying greedy argument and end-delimit them). Sorry that's not a very helpful answer

**Comment by wjwwood** [comment]
Looks like it was fixed last night:

http://ci.ros2.org/view/nightly/job/nightly_linux_coverage/418/

I wouldn't have thought this was a flakey kind of bug. Did anyone deploy or redeploy setting maybe (i.e. was master ok, but the latest had not been pushed somehow)?

**Comment by mikaelarguedas** [comment]
hmmm I guess that's on me, looks like I deployed the refactor of the paramete to that job last night (I thought I did only the ci_packaging jobs :confused: ). So it's been fixed by passing the additional ament build args before. I guess this one can be closed, we will need to reevaluate https://github.com/ros2/ci/issues/51, I think there is still a conceptual issue on the delimiter logic

**Comment by wjwwood** [comment]
Ok, I'll close this for now and reopen it if it is an issue in the coming nightlies. I'll leave #51 to track the higher level issue.
